In [4]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

In [5]:
#Question 1
from sklearn.datasets import load_digits

In [6]:
digit=load_digits()
x=digit.data
y=digit.target

In [7]:
x.shape,y.shape

((1797, 64), (1797,))

In [8]:
#Question 2
from sklearn.preprocessing import StandardScaler

In [9]:
x = StandardScaler().fit_transform(x)
x

array([[ 0.        , -0.33501649, -0.04308102, ..., -1.14664746,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  0.54856067,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  1.56568555,
         1.6951369 , -0.19600752],
       ...,
       [ 0.        , -0.33501649, -0.88456568, ..., -0.12952258,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -0.67419451, ...,  0.8876023 ,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649,  1.00877481, ...,  0.8876023 ,
        -0.26113572, -0.19600752]])

In [10]:
#Question 4
from sklearn.decomposition import PCA

In [11]:
pca = PCA(n_components = 8)
pca.fit(x)

PCA(copy=True, iterated_power='auto', n_components=8, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [12]:
princiComponent = pca.fit_transform(x)
princiComponent

array([[ 1.91417495, -0.95451808, -3.94531854, ...,  0.54827928,
        -1.4155556 ,  1.5068286 ],
       [ 0.58900336,  0.92481645,  3.92515148, ..., -0.68719202,
         1.86918224,  0.56293841],
       [ 1.30209541, -0.31768338,  3.02217418, ...,  0.91113981,
        -1.28678928,  1.14447793],
       ...,
       [ 1.02264701, -0.14829388,  2.47006376, ...,  0.02823896,
         0.39143546,  0.51599463],
       [ 1.07609191, -0.38158256, -2.45552799, ..., -0.59165252,
         1.05026844,  0.75304967],
       [-1.25762386, -2.22840993,  0.28256321, ...,  2.36000183,
        -0.36380685, -1.22761704]])

In [14]:
princiDf = pd.DataFrame(data = princiComponent , columns = ['principal component 1', 'principal component 2','principal component 3',
                                                                  'principal component 4','principal component 5','principal component 6',
                                                                  'principal component 7','principal component 8'])
princiDf
##new x

principal component 1  principal component 2  principal component 3  \
0                  1.914175              -0.954518              -3.945319   
1                  0.589003               0.924816               3.925151   
2                  1.302095              -0.317683               3.022174   
3                 -3.020792              -0.868312              -0.801324   
4                  4.528868              -1.092326               0.974817   
5                 -1.301913              -1.148700              -1.574022   
6                  1.434174              -2.957411               2.831950   
7                  0.614172               5.462926               0.658253   
8                 -1.098429              -0.666149              -0.040723   
9                 -0.537950              -0.778356              -1.569113   
10                 3.378665              -0.495247              -2.279750   
11                 2.063358               2.016867               1.539710   
12                -1.937018              -1.815583               2.801236   
13                -3.258048               2.148803              -1.616104   
14                 5.458771               0.025297               0.183338   
15                -3.877032               2.606407               1.858084   
16                 0.921337              -3.262028               3.401308   
17                 1.415401               1.953790               0.559572   
18                -0.926627               2.253682               1.533882   
19                -2.371058              -2.931696              -0.379894   
20                 2.001873              -1.319840              -2.571320   
21                 1.694928               2.075395               0.884772   
22                -3.114561              -1.059126               2.451489   
23                -1.469391               3.910483              -2.077808   
24                 4.003279              -0.321604               0.587993   
25                -0.376748               0.525194               1.356396   
26                 1.286740              -3.969266               2.542319   
27                 3.842323               3.478685              -1.568955   
28                -0.166542               0.933858               1.259679   
29                -2.014461              -2.376984              -0.707807   
...                     ...                    ...                    ...   
1767               4.958543              -1.158861               0.645966   
1768               1.008957              -3.325418              -0.583388   
1769              -0.542879              -0.492514              -3.138397   
1770              -3.314668               1.510638              -0.820645   
1771               2.128201              -2.822115               3.622910   
1772              -1.813955               1.197826              -3.114627   
1773               1.374700              -4.417942               0.543996   
1774               0.762987               0.643056               3.117922   
1775              -0.433142               3.216639               2.011557   
1776              -0.525836              -1.154524              -1.890301   
1777               5.106637              -0.288247               0.342060   
1778               5.900193              -1.710506               1.858413   
1779               1.597087               4.677134               0.470187   
1780              -5.137710              -0.192145               2.223183   
1781              -1.416062              -1.031651               1.194924   
1782              -4.272882              -1.356368               3.059985   
1783              -3.136867              -1.411733               2.239477   
1784               1.568504              -0.438407              -1.840630   
1785               0.058250               1.978443               1.806750   
1786              -0.711417               0.252797              -2.934761   
17

In [15]:
pca.explained_variance_ratio_

array([0.12033916, 0.09561054, 0.08444414, 0.06498404, 0.04860025,
       0.04213452, 0.03941949, 0.03389236])

In [16]:
#Question 3
princiDf_train,princiDf_test,y_train,y_test = train_test_split(princiDf,y,test_size = 0.3)

In [17]:
#Question 5
Reg = LogisticRegression()

In [18]:
Reg.fit(princiDf_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [19]:
predict = Reg.predict(princiDf_test)
predict

array([5, 4, 6, 1, 5, 0, 3, 2, 4, 7, 4, 4, 0, 6, 5, 9, 3, 5, 5, 1, 1, 4,
       5, 8, 1, 8, 8, 2, 6, 2, 0, 9, 6, 5, 6, 2, 5, 3, 4, 5, 4, 6, 5, 8,
       4, 5, 3, 5, 9, 3, 6, 2, 3, 4, 8, 4, 8, 2, 9, 9, 3, 3, 4, 1, 5, 6,
       2, 6, 7, 9, 3, 6, 3, 2, 0, 3, 6, 7, 6, 2, 0, 1, 0, 1, 4, 5, 5, 3,
       2, 3, 3, 1, 7, 2, 4, 2, 4, 6, 9, 0, 5, 6, 6, 4, 6, 8, 2, 8, 6, 7,
       7, 8, 1, 5, 6, 0, 7, 9, 4, 2, 6, 2, 9, 2, 7, 2, 2, 5, 3, 6, 0, 6,
       1, 1, 5, 1, 2, 0, 6, 0, 9, 0, 4, 7, 3, 5, 2, 0, 2, 9, 1, 9, 6, 8,
       0, 2, 8, 5, 0, 2, 1, 6, 0, 8, 2, 2, 9, 9, 6, 2, 3, 2, 6, 1, 9, 5,
       0, 6, 0, 4, 9, 2, 7, 7, 0, 6, 2, 5, 6, 6, 8, 9, 7, 1, 9, 9, 0, 4,
       7, 8, 4, 6, 9, 3, 6, 2, 1, 6, 9, 0, 5, 2, 4, 5, 4, 5, 0, 1, 7, 6,
       3, 2, 7, 4, 6, 4, 1, 0, 2, 3, 7, 2, 1, 0, 1, 7, 9, 4, 1, 6, 9, 9,
       9, 8, 8, 1, 9, 5, 7, 5, 7, 2, 1, 3, 6, 8, 3, 8, 5, 9, 4, 7, 7, 4,
       6, 1, 0, 5, 1, 9, 5, 6, 8, 7, 0, 8, 3, 9, 7, 6, 3, 7, 2, 6, 7, 3,
       8, 1, 9, 3, 0, 2, 2, 7, 2, 5, 2, 2, 2, 9, 0,

In [20]:
#Question 6
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [21]:
from sklearn import metrics
metrics.accuracy_score(predict, y_test)

0.8240740740740741

In [22]:
print(confusion_matrix(predict, y_test))

[[48  0  0  0  0  0  1  0  0  0]
 [ 0 43  1  1  0  0  2  0  9  1]
 [ 0  2 59  0  0  0  0  0  4  0]
 [ 0  0  0 36  0  0  0  0  4 13]
 [ 0  2  0  0 48  0  2  0  1  0]
 [ 0  0  0  1  0 47  0  0  6  1]
 [ 0  1  0  1  0  1 57  0  1  0]
 [ 0  0  2  5  2  0  0 44  1  0]
 [ 0  0  0  1  0  1  0  0 29  3]
 [ 0  7  2  5  0  3  0  0  8 34]]


In [23]:
print(classification_report(predict, y_test))

             precision    recall  f1-score   support

          0       1.00      0.98      0.99        49
          1       0.78      0.75      0.77        57
          2       0.92      0.91      0.91        65
          3       0.72      0.68      0.70        53
          4       0.96      0.91      0.93        53
          5       0.90      0.85      0.88        55
          6       0.92      0.93      0.93        61
          7       1.00      0.81      0.90        54
          8       0.46      0.85      0.60        34
          9       0.65      0.58      0.61        59

avg / total       0.85      0.82      0.83       540

